remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Portfolio
description: This website is meant to be a personal portfolio, showcasing projects that I have worked on.

collections:
  posts:
    output: true
