remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Devin Beer
description: This website is meant to be a personal portfolio, showing any personal projects that I have worked on.
