remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Devin Beer
description: Desktop Support Technician. Aspiring SysAdmin / Linux Admin.

collections:
  posts:
    output: true
